CREATE OR REPLACE WAREHOUSE NYC_TAXI_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
USE WAREHOUSE NYC_TAXI_WH;
CREATE OR REPLACE DATABASE NYC_TAXI_DB;

USE DATABASE NYC_TAXI_DB;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA FINAL;
SHOW SCHEMAS;